### ISSUE TITLE
Overall Summary (16/16)

### ISSUE THREAD

**Issue by jlag34** [LCR-8/NodeJS-Scoop#5]
You did an awesome job on your project. Your code in your server file is clear and concise. I like that you assigned a function to a route and did the logic underneath. Also, great use of array methods. It really shows your understanding of Arrays and JavaScript. Great work at getting all of the tests to pass. All in all, keep up the good work.

**Comment by LCR-8** [comment]
Many thanks,
Cheers!

L-C
